export const FETCH_PROFILE_INFO_REQUEST = "FETCH_PROFILE_INFO_REQUEST"
export const FETCH_PROFILE_INFO_SUCCESS = "FETCH_PROFILE_INFO_SUCCESS"
export const FETCH_PROFILE_INFO_ERROR = "FETCH_PROFILE_INFO_ERROR"

