export const CARD_LIST_REQUEST = "FETCH_TRACKS_REQUEST";
export const CARD_LIST_ERROR = "FETCH_TRACKS_ERROR";
export const CARD_LIST_SUCCESS = "FETCH_TRACKS_SUCCESS";

export const REORDER_CARD_LIST_REQUEST = "FETCH_TRACK_REQUEST";
export const REORDER_CARD_LIST_ERROR = "FETCH_TRACK_ERROR";
export const REORDER_CARD_LIST_SUCCESS = "FETCH_TRACK_SUCCESS";

