export const HOME = "/";
export const SIGN_UP = "/sign-up";
export const LOGIN = "/login";
export const RESET_PASSWORD = "/reset-password";
export const ACCOUNT ="/account";
export const EDIT_PROFILE = "/edit-profile"
export const PROFILE = "/profile";
export const PROFILE_EDIT ="/profile/edit"
export const EXPLORE = "/explore";
export const LIBRARY = "/library";
