export const GET_TRACKS_DATA_REQUEST = "GET_TRACKS_DATA_REQUEST"
export const GET_TRACKS_DATA_SUCCESS = "GET_TRACKS_DATA_SUCCESS"
export const GET_TRACKS_DATA_FAILURE = "GET_TRACKS_DATA_FAILURE"
export const SET_TRACKS_LIKED = "SET_TRACKS_LIKED"