export const FETCH_TRACKS_REQUEST = "FETCH_TRACKS_REQUEST";
export const FETCH_TRACKS_ERROR = "FETCH_TRACKS_ERROR";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";

export const FETCH_TRACK_REQUEST = "FETCH_TRACK_REQUEST";
export const FETCH_TRACK_ERROR = "FETCH_TRACK_ERROR";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const UPDATE_TRACK = "UPDATE_TRACK";

export const trackTypes = {
  ALL: "ALL",
  LIKED: "LIKED",
  OWNED: "OWNED"
};