export const SET_SONGS_TO_UPLOAD = "SET_SONGS_TO_UPLOAD";
export const UNSET_SONG_TO_UPLOAD = "UNSET_SONG_TO_UPLOAD";

export const UPDATE_SONG_TO_UPLOAD = "UPDATE_SONG_TO_UPLOAD";

export const UPLOAD_SONG_REQUEST = "UPLOAD_SONG_REQUEST";
export const UPLOAD_SONG_PROGRESS = "UPLOAD_SONG_PROGRESS";
export const UPLOAD_SONG_ERROR = "UPLOAD_SONG_ERROR";
export const UPLOAD_SONG_SUCCESS = "UPLOAD_SONG_SUCCESS";

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
