export const ADD_PLAYER_TRACK = "ADD_PLAYER_TRACK";
export const REMOVE_PLAYER_TRACK = "REMOVE_PLAYER_TRACK";
export const SET_NEXT_PLAYER_TRACK = "SET_NEXT_PLAYER_TRACK";
export const SET_PREVIOUS_PLAYER_TRACK = "SET_PREVIOUS_PLAYER_TRACK";