export const ADD_TRACK_TO_PLAYER = "ADD_TRACK_TO_PLAYER";
export const REMOVE_TRACK_FROM_PLAYER = "REMOVE_TRACK_FROM_PLAYER";
export const SET_NEXT_TRACK_IN_PLAYER = "SET_NEXT_TRACK_IN_PLAYER";
export const SET_PREVIOUS_TRACK_IN_PLAYER = "SET_PREVIOUS_TRACK_IN_PLAYER";
export const SET_CURRENTLY_PLAYING = "SET_CURRENTLY_PLAYING";
