export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";

export const UPDATE_PLAYLIST_REQUEST = "UPDATE_PLAYLIST_REQUEST";
export const UPDATE_PLAYLIST_ERROR = "UPDATE_PLAYLIST_ERROR";
export const UPDATE_PLAYLIST_SUCCESS = "UPDATE_PLAYLIST_SUCCESS";
export const UPDATE_PLAYLIST_TRACKS = "UPDATE_PLAYLIST_TRACKS";

export const FETCH_PLAYLISTS_REQUEST = "FETCH_PLAYLISTS_REQUEST";
export const FETCH_PLAYLISTS_ERROR = "FETCH_PLAYLISTS_ERROR";
export const FETCH_PLAYLISTS_SUCCESS = "FETCH_PLAYLISTS_SUCCESS";

export const FETCH_PLAYLIST_REQUEST = "FETCH_PLAYLIST_REQUEST";
export const FETCH_PLAYLIST_ERROR = "FETCH_PLAYLIST_ERROR";
export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";
