export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";

export const UPDATE_PLAYLIST_REQUEST = "UPDATE_PLAYLIST_REQUEST";
export const UPDATE_PLAYLIST_ERROR = "UPDATE_PLAYLIST_ERROR";
export const UPDATE_PLAYLIST_SUCCESS = "UPDATE_PLAYLIST_SUCCESS";
export const UPDATE_PLAYLIST_TRACKS = "UPDATE_PLAYLIST_TRACKS";
export const UPDATE_PLAYLIST_FOLLOWING = "UPDATE_PLAYLIST_FOLLOWING";
export const UPDATE_PLAYLIST = "UPDATE_PLAYLIST";

export const FETCH_PLAYLISTS_REQUEST = "FETCH_PLAYLISTS_REQUEST";
export const FETCH_PLAYLISTS_ERROR = "FETCH_PLAYLISTS_ERROR";
export const FETCH_PLAYLISTS_SUCCESS = "FETCH_PLAYLISTS_SUCCESS";

export const FETCH_PLAYLIST_REQUEST = "FETCH_PLAYLIST_REQUEST";
export const FETCH_PLAYLIST_ERROR = "FETCH_PLAYLIST_ERROR";
export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";

export const DELETE_PLAYLIST_REQUEST = "DELETE_PLAYLIST_REQUEST";
export const DELETE_PLAYLIST_ERROR = "DELETE_PLAYLIST_ERROR";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_POST_SUCCESS = "DELETE_PLAYLIST_POST_SUCCESS";


